# Generated by Django 5.0 on 2024-05-19 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledb',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='profiledb',
            name='profilePIC',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='user',
        ),
        migrations.AddField(
            model_name='profiledb',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profiledb',
            name='profileimg',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
